---
javascripts:
  modernizr:
    - public/javascripts/vendor/modernizr.js
  application:
    - public/javascripts/vendor/jquery.js
    - public/javascripts/vendor/jquery.rails.js
    - public/javascripts/vendor/jquery.ui.js

stylesheets:
  global:
    - public/stylesheets/global.css
  handheld:
    - public/stylesheets/handheld.css
